### PR TITLE
Small corrections with English and Greek typos and XML infelicities in Cunliffe entries

### PR DESCRIPTION
**Pull request by davidfdriscoll**
As part of a personal project to create a React dictionary app based on Cunliffe (demo [here](https://brave-bell-1f4629.netlify.app/)), I made some small corrections to the XML and Greek and English spelling in the Cunliffe XML. Thanks for sharing it!

### CODE REVIEW

**Comment by helmadik** [comment]
@gregorycrane will have to bring in my forked version for this? Ugh I'm such a complete newbie with git.

**Comment by davidfdriscoll** [comment]
> @gregorycrane will have to bring in my forked version for this? Ugh I'm such a complete newbie with git.

I could open up a PR directly on your forked version too if that’s easier.

**Comment by helmadik** [comment]
About to get on a flight. Will look at all of this sometime later this
week.
Helma Dik
Department of Classics
University of Chicago

**Comment by davidfdriscoll** [comment]
Happy to reopen this when there's interest.

**Pull request closed without merging**
